from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from octanex_mcp.config import OctaneConfig, doctor, generate_bridge_script, initialize_environment, resolve_config
from octanex_mcp.bridge import Workspace, octane_app_status


class ConfigTests(unittest.TestCase):
    def test_resolve_config_uses_environment_overrides(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            env = {
                "OCTANEX_MCP_WORKSPACE": str(root / "workspace"),
                "OCTANEX_MCP_REPO": str(root / "repo"),
                "OCTANEX_APP_PATH": str(root / "Octane X.app"),
            }
            config = resolve_config(env)
            self.assertEqual(config.workspace, root / "workspace")
            self.assertEqual(config.repo_root, root / "repo")
            self.assertEqual(config.app_path, root / "Octane X.app")

    def test_workspace_and_app_status_use_resolved_config(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            config = OctaneConfig(
                workspace=root / "workspace",
                repo_root=root / "repo",
                app_path=root / "Octane X.app",
            )
            ws = Workspace.from_config(config)
            self.assertEqual(ws.root, config.workspace)
            status = octane_app_status(config=config)
            self.assertEqual(status["workspace"], str(config.workspace))
            self.assertEqual(status["repo_root"], str(config.repo_root))
            self.assertEqual(status["app_path"], str(config.app_path))

    def test_generate_bridge_script_replaces_single_root_line(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            template = root / "bridge.lua"
            output = root / "bridge.generated.lua"
            template.write_text('local ROOT = "/Users/craig/OctaneMCP"\nlocal INBOX = ROOT .. "/inbox.json"\n', encoding="utf-8")
            config = OctaneConfig(workspace=root / "workspace", repo_root=root, app_path=root / "Octane X.app")
            generate_bridge_script(template, output, config)
            text = output.read_text(encoding="utf-8")
            self.assertIn(f'local ROOT = "{config.workspace}"', text)
            self.assertIn("Generated by `octanex-mcp init`", text)
            self.assertNotIn("/Users/craig/OctaneMCP", text)

    def test_initialize_environment_writes_configs_and_generated_bridges(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            lua_dir = root / "repo" / "octane_lua"
            lua_dir.mkdir(parents=True)
            (lua_dir / "hermes_bridge_oneshot_v2.lua").write_text('local ROOT = "/old"\n', encoding="utf-8")
            (lua_dir / "hermes_bridge_persistent_v1.lua").write_text('local ROOT = "/old"\n', encoding="utf-8")
            config = OctaneConfig(workspace=root / "workspace", repo_root=root / "repo", app_path=root / "Octane X.app")

            result = initialize_environment(config)

            self.assertTrue(result["ok"])
            self.assertTrue(config.config_json_path.exists())
            self.assertTrue(config.lua_config_path.exists())
            self.assertTrue(config.oneshot_generated_path.exists())
            self.assertTrue(config.persistent_generated_path.exists())
            payload = json.loads(config.config_json_path.read_text(encoding="utf-8"))
            self.assertEqual(payload["workspace"], str(config.workspace))
            self.assertIn(str(config.oneshot_generated_path), result["generated_bridges"])

    def test_doctor_checks_workspace_and_generated_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            lua_dir = root / "repo" / "octane_lua"
            lua_dir.mkdir(parents=True)
            (lua_dir / "hermes_bridge_oneshot_v2.lua").write_text('local ROOT = "/old"\n', encoding="utf-8")
            (lua_dir / "hermes_bridge_persistent_v1.lua").write_text('local ROOT = "/old"\n', encoding="utf-8")
            config = OctaneConfig(workspace=root / "workspace", repo_root=root / "repo", app_path=root / "Octane X.app")
            initialize_environment(config)

            result = doctor(config, create=True)

            self.assertIn("checks", result)
            checks = {item["name"]: item for item in result["checks"]}
            self.assertTrue(checks["workspace_root"]["ok"])
            self.assertTrue(checks["workspace_queue"]["ok"])
            self.assertTrue(checks["workspace_writable"]["ok"])
            self.assertTrue(checks["lua_config_generated"]["ok"])
            self.assertTrue(checks["oneshot_bridge_generated"]["ok"])


if __name__ == "__main__":
    unittest.main()
