#!/usr/bin/env python3
"""Generate a simplified ancient Greek temple OBJ.

Geometry: 3-tier stepped platform, two rows of tapered columns, an
entablature block, and a triangular pediment. Single stone material.
Writes the OBJ into the Octane X container assets dir so the sandboxed
app can read it.
"""
import math
import os
import sys

CONTAINER_ASSETS = os.path.expanduser(
    "~/Library/Containers/com.otoy.rndrviewer/Data/OctaneMCP/assets"
)
REPO_STAGING = os.path.join(os.path.dirname(__file__), "..", "OctaneMCP_staging")


def emit_box(verts, faces, cx, cy, cz, hx, hy, hz, group):
    corners = [
        (-hx, -hy, -hz), (hx, -hy, -hz), (hx, hy, -hz), (-hx, hy, -hz),
        (-hx, -hy, hz), (hx, -hy, hz), (hx, hy, hz), (-hx, hy, hz),
    ]
    base = len(verts) + 1
    for (x, y, z) in corners:
        verts.append((cx + x, cy + y, cz + z))
    quads = [
        (0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
        (3, 7, 6, 2), (0, 4, 7, 3), (1, 2, 6, 5),
    ]
    for (a, b, c, d) in quads:
        faces.append((group, (base + a, base + b, base + c)))
        faces.append((group, (base + a, base + c, base + d)))


def emit_cylinder(verts, faces, cx, cz, y0, y1, r0, r1, seg, group):
    ring0 = len(verts) + 1
    for i in range(seg):
        ang = 2 * math.pi * i / seg
        verts.append((cx + r0 * math.cos(ang), y0, cz + r0 * math.sin(ang)))
    ring1 = len(verts) + 1
    for i in range(seg):
        ang = 2 * math.pi * i / seg
        verts.append((cx + r1 * math.cos(ang), y1, cz + r1 * math.sin(ang)))
    for i in range(seg):
        a = ring0 + i
        b = ring0 + (i + 1) % seg
        c = ring1 + i
        d = ring1 + (i + 1) % seg
        faces.append((group, (a, b, d)))
        faces.append((group, (a, d, c)))
    ctop = len(verts) + 1
    verts.append((cx, y1, cz))
    cbot = len(verts) + 1
    verts.append((cx, y0, cz))
    for i in range(seg):
        a = ring1 + i
        b = ring1 + (i + 1) % seg
        faces.append((group, (a, b, ctop)))
        a2 = ring0 + i
        b2 = ring0 + (i + 1) % seg
        faces.append((group, (b2, a2, cbot)))


def emit_prism(verts, faces, base_y, W, H, z0, z1, group):
    A0 = len(verts) + 1
    verts.append((-W, base_y, z0))
    B0 = len(verts) + 1
    verts.append((W, base_y, z0))
    C0 = len(verts) + 1
    verts.append((0, base_y + H, z0))
    A1 = len(verts) + 1
    verts.append((-W, base_y, z1))
    B1 = len(verts) + 1
    verts.append((W, base_y, z1))
    C1 = len(verts) + 1
    verts.append((0, base_y + H, z1))
    faces.append((group, (A0, B0, C0)))
    faces.append((group, (A1, C1, B1)))
    faces.append((group, (A0, C0, C1)))
    faces.append((group, (A0, C1, A1)))
    faces.append((group, (B0, C0, C1)))
    faces.append((group, (B0, C1, B1)))
    faces.append((group, (A0, B0, B1)))
    faces.append((group, (A0, B1, A1)))


def build():
    verts = []
    stone = []  # group 1
    roof = []   # group 2

    # --- stepped platform (3 tiers) ---
    tiers = [
        (7.0, 4.0, 0.0, 0.5),
        (6.5, 3.5, 0.5, 0.5),
        (6.0, 3.0, 1.0, 0.5),
    ]
    for (hx, hz, y0, h) in tiers:
        emit_box(verts, stone, 0, y0 + h / 2, 0, hx, h / 2, hz, "stone")

    top_y = 1.5
    col_h = 6.0
    col_r0 = 0.45
    col_r1 = 0.38
    seg = 24
    xs = [-5, -3, -1, 1, 3, 5]
    zs = [2.7, -2.7]
    for z in zs:
        for x in xs:
            emit_cylinder(verts, stone, x, z, top_y, top_y + col_h,
                          col_r0, col_r1, seg, "stone")

    # --- entablature block on top of columns ---
    ent_y0 = top_y + col_h
    ent_h = 0.9
    emit_box(verts, stone, 0, ent_y0 + ent_h / 2, 0, 6.3, ent_h / 2, 3.2, "stone")

    # --- pediment (triangular prism) on top of entablature ---
    ped_base = ent_y0 + ent_h
    emit_prism(verts, roof, ped_base, 6.3, 2.2, -3.2, 3.2, "roof")

    return verts, {"stone": stone, "roof": roof}


def write_obj(path):
    verts, groups = build()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("# ancient temple (generated by gen_temple_obj.py)\n")
        f.write("mtllib temple.mtl\n")
        for (x, y, z) in verts:
            f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
        for gname in ("stone", "roof"):
            f.write(f"usemtl {gname}\n")
            f.write(f"g {gname}\n")
            for (_g, tri) in groups[gname]:
                f.write("f " + " ".join(str(i) for i in tri) + "\n")
    return path, len(verts), sum(len(v) for v in groups.values())


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        CONTAINER_ASSETS, "temple.obj")
    # also keep a repo-side copy for inspection
    repo_copy = os.path.join(REPO_STAGING, "temple.obj")
    p, nv, nf = write_obj(out)
    write_obj(repo_copy)
    print(f"wrote {p}: {nv} verts, {nf} faces")
