from __future__ import annotations

import json
import os
import re
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

DEFAULT_APP_PATH = Path("/Applications/Octane X.app")
DEFAULT_WORKSPACE = Path.home() / "Library" / "Containers" / "com.otoy.rndrviewer" / "Data" / "OctaneMCP"
DEFAULT_REPO_ROOT = Path(__file__).resolve().parents[2]

ENV_WORKSPACE = "OCTANEX_MCP_WORKSPACE"
ENV_REPO = "OCTANEX_MCP_REPO"
ENV_APP_PATH = "OCTANEX_APP_PATH"
ENV_APP_PATH_LEGACY = "OCTANE_APP_PATH"

WORKSPACE_DIRS = ("queue", "processing", "processed", "failed", "results", "artifacts", "assets", "renders", "scenes")


@dataclass(frozen=True)
class OctaneConfig:
    """Resolved local paths for the Octane X MCP bridge."""

    workspace: Path
    repo_root: Path
    app_path: Path

    @property
    def lua_dir(self) -> Path:
        return self.repo_root / "octane_lua"

    @property
    def config_json_path(self) -> Path:
        return self.workspace / "octanex-mcp.config.json"

    @property
    def lua_config_path(self) -> Path:
        return self.lua_dir / "config.generated.lua"

    @property
    def oneshot_generated_path(self) -> Path:
        return self.lua_dir / "hermes_bridge_oneshot.generated.lua"

    @property
    def persistent_generated_path(self) -> Path:
        return self.lua_dir / "hermes_bridge_persistent.generated.lua"


def _path_from_env(env: Mapping[str, str], name: str, default: Path) -> Path:
    raw = env.get(name)
    if raw is None or not raw.strip():
        return default
    return Path(raw).expanduser()


def resolve_config(env: Mapping[str, str] | None = None, *, repo_root: Path | None = None) -> OctaneConfig:
    """Resolve Octane MCP paths from environment variables and portable defaults.

    Environment variables:
    - OCTANEX_MCP_WORKSPACE: command queue workspace visible to Octane Lua.
    - OCTANEX_MCP_REPO: repository root used to locate/generate Lua bridge scripts.
    - OCTANEX_APP_PATH: Octane X .app bundle path.
    - OCTANE_APP_PATH: backwards-compatible alias for OCTANEX_APP_PATH.
    """

    env = os.environ if env is None else env
    default_repo = repo_root or DEFAULT_REPO_ROOT
    app_default = _path_from_env(env, ENV_APP_PATH_LEGACY, DEFAULT_APP_PATH)
    return OctaneConfig(
        workspace=_path_from_env(env, ENV_WORKSPACE, DEFAULT_WORKSPACE),
        repo_root=_path_from_env(env, ENV_REPO, default_repo),
        app_path=_path_from_env(env, ENV_APP_PATH, app_default),
    )


def workspace_paths(config: OctaneConfig) -> dict[str, Path]:
    paths = {"root": config.workspace}
    paths.update({name: config.workspace / name for name in WORKSPACE_DIRS})
    paths.update({
        "inbox": config.workspace / "inbox.json",
        "status": config.workspace / "status.json",
        "bridge_log": config.workspace / "bridge.log",
    })
    return paths


def ensure_workspace(config: OctaneConfig) -> None:
    for path in [config.workspace, *(config.workspace / name for name in WORKSPACE_DIRS)]:
        path.mkdir(parents=True, exist_ok=True)


def _lua_string(value: Path | str) -> str:
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_lua_config(config: OctaneConfig) -> str:
    return "\n".join([
        "-- Generated by `octanex-mcp init`; safe to overwrite.",
        "local config = {}",
        f"config.ROOT = {_lua_string(config.workspace)}",
        f"config.REPO_ROOT = {_lua_string(config.repo_root)}",
        f"config.APP_PATH = {_lua_string(config.app_path)}",
        "return config",
        "",
    ])


def write_json_config(config: OctaneConfig) -> Path:
    ensure_workspace(config)
    payload = {
        "workspace": str(config.workspace),
        "repo_root": str(config.repo_root),
        "app_path": str(config.app_path),
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "environment": {
            ENV_WORKSPACE: str(config.workspace),
            ENV_REPO: str(config.repo_root),
            ENV_APP_PATH: str(config.app_path),
        },
    }
    config.config_json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return config.config_json_path


def write_lua_config(config: OctaneConfig) -> Path:
    config.lua_dir.mkdir(parents=True, exist_ok=True)
    config.lua_config_path.write_text(render_lua_config(config), encoding="utf-8")
    return config.lua_config_path


_ROOT_RE = re.compile(r"local\s+ROOT\s*=\s*[^\n]+")


def generate_bridge_script(template_path: Path, output_path: Path, config: OctaneConfig) -> Path:
    """Copy a bridge script while injecting the resolved workspace ROOT."""

    text = template_path.read_text(encoding="utf-8")
    replacement = f"local ROOT = {_lua_string(config.workspace)}"
    text, count = _ROOT_RE.subn(replacement, text, count=1)
    if count != 1:
        raise ValueError(f"could not find a single `local ROOT = ...` line in {template_path}")
    banner = "-- Generated by `octanex-mcp init` from " + template_path.name + "; safe to overwrite.\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(banner + text, encoding="utf-8")
    return output_path


def initialize_environment(config: OctaneConfig | None = None) -> dict[str, Any]:
    config = resolve_config() if config is None else config
    ensure_workspace(config)
    json_path = write_json_config(config)
    lua_config_path = write_lua_config(config)
    generated: list[str] = []
    templates = [
        (config.lua_dir / "hermes_bridge_oneshot_v2.lua", config.oneshot_generated_path),
        (config.lua_dir / "hermes_bridge_persistent_v1.lua", config.persistent_generated_path),
    ]
    for template, output in templates:
        if template.exists():
            generated.append(str(generate_bridge_script(template, output, config)))
    return {
        "ok": True,
        "workspace": str(config.workspace),
        "repo_root": str(config.repo_root),
        "app_path": str(config.app_path),
        "config_json": str(json_path),
        "lua_config": str(lua_config_path),
        "generated_bridges": generated,
    }


def _check(name: str, ok: bool, *, path: Path | None = None, message: str = "") -> dict[str, Any]:
    item: dict[str, Any] = {"name": name, "ok": bool(ok)}
    if path is not None:
        item["path"] = str(path)
    if message:
        item["message"] = message
    return item


def _writable(path: Path) -> tuple[bool, str]:
    try:
        path.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile("w", dir=path, prefix=".octanex-doctor-", delete=False) as handle:
            handle.write("ok\n")
            temp_path = Path(handle.name)
        temp_path.unlink(missing_ok=True)
        return True, "writable"
    except Exception as exc:  # pragma: no cover - platform/permission-specific
        return False, str(exc)


def doctor(config: OctaneConfig | None = None, *, create: bool = True) -> dict[str, Any]:
    """Run local diagnostics for Octane app paths, workspace, bridge files, and status."""

    config = resolve_config() if config is None else config
    if create:
        ensure_workspace(config)

    exe = config.app_path / "Contents" / "MacOS" / "Octane X"
    plist = config.app_path / "Contents" / "Info.plist"
    checks: list[dict[str, Any]] = [
        _check("octane_app_bundle", config.app_path.exists(), path=config.app_path),
        _check("octane_executable", exe.exists(), path=exe),
        _check("octane_info_plist", plist.exists(), path=plist),
        _check("repo_root", config.repo_root.exists(), path=config.repo_root),
        _check("octane_lua_dir", config.lua_dir.exists(), path=config.lua_dir),
    ]

    for name, path in workspace_paths(config).items():
        if name in {"inbox", "status", "bridge_log"}:
            checks.append(_check(f"workspace_{name}_parent", path.parent.exists(), path=path.parent))
        else:
            checks.append(_check(f"workspace_{name}", path.exists(), path=path))

    writable, writable_message = _writable(config.workspace) if create or config.workspace.exists() else (False, "workspace does not exist")
    checks.append(_check("workspace_writable", writable, path=config.workspace, message=writable_message))

    checks.extend([
        _check("lua_config_generated", config.lua_config_path.exists(), path=config.lua_config_path),
        _check("oneshot_bridge_generated", config.oneshot_generated_path.exists(), path=config.oneshot_generated_path),
        _check("persistent_bridge_generated", config.persistent_generated_path.exists(), path=config.persistent_generated_path),
    ])

    status_path = config.workspace / "status.json"
    bridge_status: dict[str, Any] = {"seen": False, "path": str(status_path)}
    if status_path.exists():
        try:
            bridge_status = json.loads(status_path.read_text(encoding="utf-8"))
            bridge_status.setdefault("seen", True)
            checks.append(_check("bridge_status_json", True, path=status_path))
        except Exception as exc:
            checks.append(_check("bridge_status_json", False, path=status_path, message=str(exc)))
    else:
        checks.append(_check("bridge_status_json", False, path=status_path, message="No status file yet; run a bridge script in Octane X."))

    ok = all(item["ok"] for item in checks if item["name"] not in {"bridge_status_json", "lua_config_generated", "oneshot_bridge_generated", "persistent_bridge_generated"})
    return {
        "ok": ok,
        "config": {
            "workspace": str(config.workspace),
            "repo_root": str(config.repo_root),
            "app_path": str(config.app_path),
        },
        "checks": checks,
        "bridge_status": bridge_status,
        "next_steps": [
            "Run `octanex-mcp init` to generate Lua bridge files." if not config.oneshot_generated_path.exists() else "Run the generated one-shot bridge in Octane X when commands are queued.",
            f"One-shot bridge: {config.oneshot_generated_path}",
            f"Persistent bridge: {config.persistent_generated_path}",
        ],
    }
