from __future__ import annotations

import math
from pathlib import Path
from typing import Any, Iterable

from .bridge import Workspace


def _safe_name(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in name) or "visual"


class ObjBuilder:
    def __init__(self, object_name: str):
        self.object_name = _safe_name(object_name)
        self.lines: list[str] = [f"# Generated by octanex-mcp visualizer", f"o {self.object_name}"]
        self.vertex_count = 0

    def add_box(
        self,
        *,
        center: tuple[float, float, float],
        size: tuple[float, float, float],
        material: str = "default",
    ) -> None:
        cx, cy, cz = center
        sx, sy, sz = (max(float(v), 1e-4) / 2.0 for v in size)
        vertices = [
            (cx - sx, cy - sy, cz - sz),
            (cx + sx, cy - sy, cz - sz),
            (cx + sx, cy + sy, cz - sz),
            (cx - sx, cy + sy, cz - sz),
            (cx - sx, cy - sy, cz + sz),
            (cx + sx, cy - sy, cz + sz),
            (cx + sx, cy + sy, cz + sz),
            (cx - sx, cy + sy, cz + sz),
        ]
        self.lines.append(f"usemtl {material}")
        for x, y, z in vertices:
            self.lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        i = self.vertex_count + 1
        faces = [
            (i, i + 1, i + 2, i + 3),
            (i + 4, i + 7, i + 6, i + 5),
            (i, i + 4, i + 5, i + 1),
            (i + 1, i + 5, i + 6, i + 2),
            (i + 2, i + 6, i + 7, i + 3),
            (i + 4, i, i + 3, i + 7),
        ]
        for face in faces:
            self.lines.append("f " + " ".join(str(v) for v in face))
        self.vertex_count += 8

    def add_surface(
        self,
        *,
        vertices: list[list[tuple[float, float, float]]],
        material: str = "default",
    ) -> None:
        if not vertices or not vertices[0]:
            return
        rows = len(vertices)
        cols = len(vertices[0])
        start = self.vertex_count + 1
        self.lines.append(f"usemtl {material}")
        for row in vertices:
            for x, y, z in row:
                self.lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        for r in range(rows - 1):
            for c in range(cols - 1):
                a = start + r * cols + c
                b = start + r * cols + c + 1
                d = start + (r + 1) * cols + c
                e = start + (r + 1) * cols + c + 1
                self.lines.append(f"f {a} {b} {e} {d}")
        self.vertex_count += rows * cols

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"

    def add_ellipsoid(
        self,
        *,
        center: tuple[float, float, float],
        radii: tuple[float, float, float],
        segments_u: int = 42,
        segments_v: int = 22,
        material: str = "default",
    ) -> None:
        cx, cy, cz = center
        rx, ry, rz = radii
        segments_u = max(8, int(segments_u))
        segments_v = max(4, int(segments_v))
        start = self.vertex_count + 1
        self.lines.append(f"usemtl {material}")
        for j in range(segments_v + 1):
            v = math.pi * j / segments_v
            for i in range(segments_u):
                u = 2.0 * math.pi * i / segments_u
                x = cx + rx * math.sin(v) * math.cos(u)
                y = cy + ry * math.sin(v) * math.sin(u)
                z = cz + rz * math.cos(v)
                self.lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        for j in range(segments_v):
            for i in range(segments_u):
                a = start + j * segments_u + i
                b = start + j * segments_u + ((i + 1) % segments_u)
                c = start + (j + 1) * segments_u + ((i + 1) % segments_u)
                d = start + (j + 1) * segments_u + i
                self.lines.append(f"f {a} {b} {c} {d}")
        self.vertex_count += (segments_v + 1) * segments_u

    def add_voxel_ring(
        self,
        *,
        center: tuple[float, float, float],
        radius: float,
        voxel_size: float = 0.08,
        count: int = 56,
        material: str = "default",
    ) -> None:
        cx, cy, cz = center
        count = max(8, int(count))
        for k in range(count):
            angle = 2.0 * math.pi * k / count
            self.add_box(
                center=(cx + radius * math.cos(angle), cy, cz + radius * math.sin(angle)),
                size=(voxel_size, voxel_size, voxel_size),
                material=material,
            )


def create_bar_chart_obj(
    values: Iterable[float],
    *,
    name: str = "visual_bar_chart",
    workspace: Workspace = Workspace(),
) -> dict[str, Any]:
    """Create a simple 3D bar-chart OBJ.

    This deliberately uses one mesh: it is robust with the current Octane bridge
    and makes data immediately visible as spatial geometry.
    """
    workspace.ensure()
    vals = [float(v) for v in values]
    if not vals:
        raise ValueError("values must not be empty")
    if len(vals) > 64:
        raise ValueError("bar chart supports up to 64 values for now")
    max_abs = max(abs(v) for v in vals) or 1.0
    scale = 2.6 / max_abs
    chart_width = max(3.0, len(vals) * 0.75)
    b = ObjBuilder(name)
    # Base plate and zero line.
    b.add_box(center=(0, 0, -0.035), size=(chart_width + 0.6, 1.1, 0.07), material="base")
    b.add_box(center=(0, -0.58, 0.02), size=(chart_width + 0.7, 0.04, 0.04), material="axis")
    start_x = -((len(vals) - 1) * 0.75) / 2.0
    for idx, value in enumerate(vals):
        height = abs(value) * scale
        z = height / 2.0 if value >= 0 else -height / 2.0
        x = start_x + idx * 0.75
        mat = "positive" if value >= 0 else "negative"
        b.add_box(center=(x, 0, z), size=(0.46, 0.65, max(height, 0.04)), material=mat)
    path = workspace.assets_dir / f"{_safe_name(name)}.obj"
    path.write_text(b.text())
    return {"path": str(path), "name": _safe_name(name), "values": vals, "kind": "bar_chart"}


_ALLOWED_NAMES: dict[str, Any] = {
    "abs": abs,
    "min": min,
    "max": max,
    "sin": math.sin,
    "cos": math.cos,
    "tan": math.tan,
    "sqrt": math.sqrt,
    "log": math.log,
    "exp": math.exp,
    "pow": pow,
    "pi": math.pi,
    "e": math.e,
}


def _eval_surface_expr(expr: str, x: float, y: float) -> float:
    allowed = dict(_ALLOWED_NAMES)
    allowed.update({"x": x, "y": y, "r": math.sqrt(x * x + y * y)})
    return float(eval(expr, {"__builtins__": {}}, allowed))


def create_surface_obj(
    expression: str,
    *,
    name: str = "visual_math_surface",
    x_range: tuple[float, float] = (-3.0, 3.0),
    y_range: tuple[float, float] = (-3.0, 3.0),
    steps: int = 36,
    workspace: Workspace = Workspace(),
) -> dict[str, Any]:
    """Create a height-field surface OBJ from a restricted math expression.

    Expression may use x, y, r and a small allowlist of math functions.
    """
    workspace.ensure()
    steps = max(6, min(int(steps), 80))
    xmin, xmax = map(float, x_range)
    ymin, ymax = map(float, y_range)
    raw: list[list[tuple[float, float, float]]] = []
    z_values: list[float] = []
    for iy in range(steps + 1):
        row: list[tuple[float, float, float]] = []
        y = ymin + (ymax - ymin) * iy / steps
        for ix in range(steps + 1):
            x = xmin + (xmax - xmin) * ix / steps
            try:
                z = _eval_surface_expr(expression, x, y)
                if not math.isfinite(z):
                    z = 0.0
            except Exception:
                z = 0.0
            z = max(min(z, 10.0), -10.0)
            z_values.append(z)
            row.append((x, y, z))
        raw.append(row)
    max_abs = max(abs(z) for z in z_values) or 1.0
    z_scale = 1.6 / max_abs
    vertices = [[(x, y, z * z_scale) for x, y, z in row] for row in raw]
    b = ObjBuilder(name)
    b.add_box(center=(0, 0, -0.06), size=(abs(xmax - xmin) + 0.4, abs(ymax - ymin) + 0.4, 0.04), material="base")
    b.add_surface(vertices=vertices, material="surface")
    path = workspace.assets_dir / f"{_safe_name(name)}.obj"
    path.write_text(b.text())
    return {
        "path": str(path),
        "name": _safe_name(name),
        "expression": expression,
        "x_range": [xmin, xmax],
        "y_range": [ymin, ymax],
        "steps": steps,
        "kind": "surface",
    }


def create_avatar_face_obj(
    *,
    name: str = "hermes_avatar_face",
    workspace: Workspace = Workspace(),
) -> dict[str, Any]:
    """Create a simple non-human Hermes avatar face for use as a scene guide."""
    workspace.ensure()
    safe = _safe_name(name)
    b = ObjBuilder(safe)
    b.add_ellipsoid(center=(0, 0, 1.25), radii=(0.95, 0.28, 1.18), material="face")
    b.add_box(center=(0, -0.28, 2.55), size=(0.22, 0.12, 0.25), material="crest")
    b.add_box(center=(0, -0.30, 0.05), size=(0.36, 0.12, 0.16), material="chin")
    for x in (-0.36, 0.36):
        b.add_box(center=(x, -0.42, 1.55), size=(0.25, 0.11, 0.12), material="eye")
        b.add_box(center=(x, -0.50, 1.55), size=(0.08, 0.08, 0.08), material="pupil")
    for i, x in enumerate([-0.32, -0.16, 0.0, 0.16, 0.32]):
        z = 0.84 - 0.10 * math.cos((i - 2) * math.pi / 4)
        b.add_box(center=(x, -0.43, z), size=(0.12, 0.10, 0.08), material="mouth")
    b.add_voxel_ring(center=(0, 0.08, 1.72), radius=1.35, voxel_size=0.08, count=56, material="halo")
    for i in range(4):
        b.add_box(center=(1.55 + 0.33 * i, -0.05, 1.1 + 0.18 * i), size=(0.22, 0.08, 0.16), material="thought")
    b.add_box(center=(0, 0, -0.08), size=(2.5, 1.05, 0.08), material="base")
    for x in (-0.78, 0.78):
        b.add_box(center=(x, -0.05, 2.15), size=(0.08, 0.08, 0.62), material="antenna")
        b.add_box(center=(x, -0.05, 2.52), size=(0.18, 0.18, 0.18), material="antenna")
    path = workspace.assets_dir / f"{safe}.obj"
    path.write_text(b.text())
    return {"path": str(path), "name": safe, "kind": "avatar_face"}


def scene_commands_for_asset(asset: dict[str, Any], *, material_name: str, color: list[float]) -> list[dict[str, Any]]:
    return [
        {"op": "import_geometry", "payload": {"path": asset["path"], "format": "obj", "name": asset["name"]}},
        {"op": "create_material", "payload": {"name": material_name, "kind": "glossy", "color": color, "roughness": 0.2}},
        {"op": "assign_material", "payload": {"object_name": asset["name"], "material_name": material_name}},
        {"op": "set_camera", "payload": {"position": [4.2, -5.0, 3.0], "target": [0.0, 0.0, 0.5], "fov": 45}},
        {"op": "set_lighting", "payload": {"preset": "soft_studio"}},
        {"op": "start_render", "payload": {"samples": 128, "width": 1280, "height": 1280}},
    ]
