from __future__ import annotations

import math
from pathlib import Path
from typing import Any, Iterable

from .bridge import Workspace


def _safe_name(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in name) or "visual"


class ObjBuilder:
    def __init__(self, object_name: str):
        self.object_name = _safe_name(object_name)
        self.lines: list[str] = [f"# Generated by octanex-mcp visualizer", f"o {self.object_name}"]
        self.vertex_count = 0

        self._points: list[tuple[float, float, float]] = []

    def _record_points(self, points: Iterable[tuple[float, float, float]]) -> None:
        self._points.extend((float(x), float(y), float(z)) for x, y, z in points)

    def add_box(
        self,
        *,
        center: tuple[float, float, float],
        size: tuple[float, float, float],
        material: str = "default",
    ) -> None:
        cx, cy, cz = center
        sx, sy, sz = (max(float(v), 1e-4) / 2.0 for v in size)
        vertices = [
            (cx - sx, cy - sy, cz - sz),
            (cx + sx, cy - sy, cz - sz),
            (cx + sx, cy + sy, cz - sz),
            (cx - sx, cy + sy, cz - sz),
            (cx - sx, cy - sy, cz + sz),
            (cx + sx, cy - sy, cz + sz),
            (cx + sx, cy + sy, cz + sz),
            (cx - sx, cy + sy, cz + sz),
        ]
        self.lines.append(f"usemtl {material}")
        self._record_points(vertices)
        for x, y, z in vertices:
            self.lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        i = self.vertex_count + 1
        faces = [
            (i, i + 1, i + 2, i + 3),
            (i + 4, i + 7, i + 6, i + 5),
            (i, i + 4, i + 5, i + 1),
            (i + 1, i + 5, i + 6, i + 2),
            (i + 2, i + 6, i + 7, i + 3),
            (i + 4, i, i + 3, i + 7),
        ]
        for face in faces:
            self.lines.append("f " + " ".join(str(v) for v in face))
        self.vertex_count += 8

    def add_surface(
        self,
        *,
        vertices: list[list[tuple[float, float, float]]],
        material: str = "default",
    ) -> None:
        if not vertices or not vertices[0]:
            return
        rows = len(vertices)
        cols = len(vertices[0])
        start = self.vertex_count + 1
        self.lines.append(f"usemtl {material}")
        self._record_points(point for row in vertices for point in row)
        for row in vertices:
            for x, y, z in row:
                self.lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        for r in range(rows - 1):
            for c in range(cols - 1):
                a = start + r * cols + c
                b = start + r * cols + c + 1
                d = start + (r + 1) * cols + c
                e = start + (r + 1) * cols + c + 1
                self.lines.append(f"f {a} {b} {e} {d}")
        self.vertex_count += rows * cols

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"

    def bounds(self) -> dict[str, Any]:
        return bounds_from_points(self._points)

    def add_ellipsoid(
        self,
        *,
        center: tuple[float, float, float],
        radii: tuple[float, float, float],
        segments_u: int = 42,
        segments_v: int = 22,
        material: str = "default",
    ) -> None:
        cx, cy, cz = center
        rx, ry, rz = radii
        segments_u = max(8, int(segments_u))
        segments_v = max(4, int(segments_v))
        start = self.vertex_count + 1
        self.lines.append(f"usemtl {material}")
        points: list[tuple[float, float, float]] = []
        for j in range(segments_v + 1):
            v = math.pi * j / segments_v
            for i in range(segments_u):
                u = 2.0 * math.pi * i / segments_u
                x = cx + rx * math.sin(v) * math.cos(u)
                y = cy + ry * math.sin(v) * math.sin(u)
                z = cz + rz * math.cos(v)
                points.append((x, y, z))
                self.lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        self._record_points(points)
        for j in range(segments_v):
            for i in range(segments_u):
                a = start + j * segments_u + i
                b = start + j * segments_u + ((i + 1) % segments_u)
                c = start + (j + 1) * segments_u + ((i + 1) % segments_u)
                d = start + (j + 1) * segments_u + i
                self.lines.append(f"f {a} {b} {c} {d}")
        self.vertex_count += (segments_v + 1) * segments_u

    def add_voxel_ring(
        self,
        *,
        center: tuple[float, float, float],
        radius: float,
        voxel_size: float = 0.08,
        count: int = 56,
        material: str = "default",
    ) -> None:
        cx, cy, cz = center
        count = max(8, int(count))
        for k in range(count):
            angle = 2.0 * math.pi * k / count
            self.add_box(
                center=(cx + radius * math.cos(angle), cy, cz + radius * math.sin(angle)),
                size=(voxel_size, voxel_size, voxel_size),
                material=material,
            )

    def add_cone(
        self,
        *,
        center: tuple[float, float, float],
        radius: float,
        height: float,
        segments: int = 24,
        cap: bool = True,
        material: str = "default",
    ) -> None:
        cx, cy, cz = center
        radius = max(float(radius), 1e-4)
        half_h = max(float(height), 1e-4) / 2.0
        segments = max(4, int(segments))
        start = self.vertex_count + 1
        self.lines.append(f"usemtl {material}")
        points: list[tuple[float, float, float]] = []
        # Rim vertices (bottom)
        for i in range(segments):
            angle = 2.0 * math.pi * i / segments
            point = (cx + radius * math.cos(angle), cy + radius * math.sin(angle), cz - half_h)
            points.append(point)
            self.lines.append(f"v {point[0]:.6f} {point[1]:.6f} {point[2]:.6f}")
        # Apex
        apex = start + segments
        point = (cx, cy, cz + half_h)
        points.append(point)
        self.lines.append(f"v {point[0]:.6f} {point[1]:.6f} {point[2]:.6f}")
        self._record_points(points)
        # Side faces
        for i in range(segments):
            a = start + i
            b = start + ((i + 1) % segments)
            self.lines.append(f"f {a} {apex} {b}")
        # Bottom cap (fan)
        for i in range(segments):
            c = start
            d = start + ((i + 1) % segments)
            self.lines.append(f"f {c} {d} {start + segments}")
        self.vertex_count += segments + 1

    def add_arrow(
        self,
        *,
        start_point: tuple[float, float, float],
        end_point: tuple[float, float, float],
        shaft_radius: float = 0.05,
        head_radius: float = 0.15,
        head_height: float = 0.3,
        segments: int = 12,
        material: str = "default",
    ) -> None:
        sx, sy, sz = start_point
        ex, ey, ez = end_point
        dx = ex - sx
        dy = ey - sy
        dz = ez - sz
        length = math.sqrt(dx * dx + dy * dy + dz * dz) or 1e-4
        nx, ny, nz = dx / length, dy / length, dz / length
        shaft_r = max(float(shaft_radius), 1e-4)
        head_r = max(float(head_radius), shaft_r * 1.2)
        h_head = min(float(head_height), length * 0.5)
        segments = max(4, int(segments))
        start_v = self.vertex_count + 1
        self.lines.append(f"usemtl {material}")
        points: list[tuple[float, float, float]] = []

        def local_xyz(ix, iy, iz) -> tuple[float, float, float]:
            return (sx + ix * nx + iy * nx + iz, sy + ix * ny + iy * ny + iz, sz + ix * nz + iy * nz)

        # Shaft vertices
        for i in range(segments):
            angle = 2.0 * math.pi * i / segments
            cos_a = math.cos(angle)
            sin_a = math.sin(angle)
            perp_x = -ny * sin_a + nz * cos_a
            perp_y = nx * sin_a
            perp_z = -nz * sin_a + ny * cos_a
            for z_off in (0.0, length - h_head):
                vx = sx + nx * z_off + perp_x * shaft_r
                vy = sy + ny * z_off + perp_y * shaft_r
                vz = sz + nz * z_off + perp_z * shaft_r
                points.append((vx, vy, vz))
                self.lines.append(f"v {vx:.6f} {vy:.6f} {vz:.6f}")
        shaft_end = start_v + segments
        # Shaft side faces
        for i in range(segments):
            a = start_v + i
            b = start_v + ((i + 1) % segments)
            c = shaft_end + ((i + 1) % segments)
            d = shaft_end + i
            self.lines.append(f"f {a} {b} {c} {d}")
        # Add apex
        apex = shaft_end + segments
        points.append((ex, ey, ez))
        self.lines.append(f"v {ex:.6f} {ey:.6f} {ez:.6f}")
        self._record_points(points)
        for i in range(segments):
            a = shaft_end + i
            b = shaft_end + ((i + 1) % segments)
            self.lines.append(f"f {a} {b} {apex}")
        self.vertex_count += segments * 2 + 1

    def add_cylinder(
        self,
        *,
        center: tuple[float, float, float],
        radius: float,
        height: float,
        segments: int = 32,
        material: str = "default",
    ) -> None:
        cx, cy, cz = center
        radius = max(float(radius), 1e-4)
        half_h = max(float(height), 1e-4) / 2.0
        segments = max(8, int(segments))
        start = self.vertex_count + 1
        self.lines.append(f"usemtl {material}")
        points: list[tuple[float, float, float]] = []
        for z in (cz - half_h, cz + half_h):
            for i in range(segments):
                angle = 2.0 * math.pi * i / segments
                point = (cx + radius * math.cos(angle), cy + radius * math.sin(angle), z)
                points.append(point)
                self.lines.append(f"v {point[0]:.6f} {point[1]:.6f} {point[2]:.6f}")
        bottom_center = start + segments * 2
        top_center = bottom_center + 1
        points.extend([(cx, cy, cz - half_h), (cx, cy, cz + half_h)])
        self.lines.append(f"v {cx:.6f} {cy:.6f} {cz - half_h:.6f}")
        self.lines.append(f"v {cx:.6f} {cy:.6f} {cz + half_h:.6f}")
        self._record_points(points)
        for i in range(segments):
            a = start + i
            b = start + ((i + 1) % segments)
            c = start + segments + ((i + 1) % segments)
            d = start + segments + i
            self.lines.append(f"f {a} {b} {c} {d}")
            self.lines.append(f"f {bottom_center} {b} {a}")
            self.lines.append(f"f {top_center} {d} {c}")
        self.vertex_count += segments * 2 + 2


def _round6(value: float) -> float:
    rounded = round(float(value), 6)
    return 0.0 if rounded == -0.0 else rounded


def bounds_from_points(points: Iterable[tuple[float, float, float]]) -> dict[str, Any]:
    pts = [(float(x), float(y), float(z)) for x, y, z in points]
    if not pts:
        pts = [(0.0, 0.0, 0.0)]
    mins = [min(point[i] for point in pts) for i in range(3)]
    maxs = [max(point[i] for point in pts) for i in range(3)]
    center = [(mins[i] + maxs[i]) / 2.0 for i in range(3)]
    radius = max(math.dist(center, point) for point in pts) or 1.0
    return {
        "min": [_round6(value) for value in mins],
        "max": [_round6(value) for value in maxs],
        "center": [_round6(value) for value in center],
        "radius": _round6(radius),
    }


def camera_for_bounds(
    bounds: dict[str, Any],
    *,
    view: str = "iso",
    margin: float = 1.35,
    fov: float = 45.0,
) -> dict[str, Any]:
    center = [float(value) for value in bounds.get("center", [0.0, 0.0, 0.0])]
    radius = max(float(bounds.get("radius", 1.0)), 0.1)
    directions = {
        "iso": (0.72, -0.86, 0.58),
        "front": (0.0, -1.0, 0.0),
        "top": (0.0, -0.01, 1.0),
        "side": (1.0, -0.02, 0.12),
    }
    dx, dy, dz = directions.get(view, directions["iso"])
    length = math.sqrt(dx * dx + dy * dy + dz * dz) or 1.0
    direction = [dx / length, dy / length, dz / length]
    safe_fov = max(min(float(fov), 120.0), 5.0)
    distance = max(radius * max(float(margin), 0.1) / math.sin(math.radians(safe_fov) / 2.0), radius * 2.0)
    position = [center[i] + direction[i] * distance for i in range(3)]
    return {"position": [_round6(value) for value in position], "target": [_round6(value) for value in center], "fov": safe_fov}


def create_bar_chart_obj(
    values: Iterable[float],
    *,
    name: str = "visual_bar_chart",
    workspace: Workspace = Workspace(),
) -> dict[str, Any]:
    """Create a simple 3D bar-chart OBJ.

    This deliberately uses one mesh: it is robust with the current Octane bridge
    and makes data immediately visible as spatial geometry.
    """
    workspace.ensure()
    vals = [float(v) for v in values]
    if not vals:
        raise ValueError("values must not be empty")
    if len(vals) > 64:
        raise ValueError("bar chart supports up to 64 values for now")
    max_abs = max(abs(v) for v in vals) or 1.0
    scale = 2.6 / max_abs
    chart_width = max(3.0, len(vals) * 0.75)
    b = ObjBuilder(name)
    # Base plate and zero line.
    b.add_box(center=(0, 0, -0.035), size=(chart_width + 0.6, 1.1, 0.07), material="base")
    b.add_box(center=(0, -0.58, 0.02), size=(chart_width + 0.7, 0.04, 0.04), material="axis")
    start_x = -((len(vals) - 1) * 0.75) / 2.0
    for idx, value in enumerate(vals):
        height = abs(value) * scale
        z = height / 2.0 if value >= 0 else -height / 2.0
        x = start_x + idx * 0.75
        mat = "positive" if value >= 0 else "negative"
        b.add_box(center=(x, 0, z), size=(0.46, 0.65, max(height, 0.04)), material=mat)
    path = workspace.assets_dir / f"{_safe_name(name)}.obj"
    path.write_text(b.text())
    return {"path": str(path), "name": _safe_name(name), "values": vals, "kind": "bar_chart", "bounds": b.bounds()}


_ALLOWED_NAMES: dict[str, Any] = {
    "abs": abs,
    "min": min,
    "max": max,
    "sin": math.sin,
    "cos": math.cos,
    "tan": math.tan,
    "sqrt": math.sqrt,
    "log": math.log,
    "exp": math.exp,
    "pow": pow,
    "pi": math.pi,
    "e": math.e,
}


def _eval_surface_expr(expr: str, x: float, y: float) -> float:
    allowed = dict(_ALLOWED_NAMES)
    allowed.update({"x": x, "y": y, "r": math.sqrt(x * x + y * y)})
    return float(eval(expr, {"__builtins__": {}}, allowed))


def create_surface_obj(
    expression: str,
    *,
    name: str = "visual_math_surface",
    x_range: tuple[float, float] = (-3.0, 3.0),
    y_range: tuple[float, float] = (-3.0, 3.0),
    steps: int = 36,
    workspace: Workspace = Workspace(),
) -> dict[str, Any]:
    """Create a height-field surface OBJ from a restricted math expression.

    Expression may use x, y, r and a small allowlist of math functions.
    """
    workspace.ensure()
    steps = max(6, min(int(steps), 80))
    xmin, xmax = map(float, x_range)
    ymin, ymax = map(float, y_range)
    raw: list[list[tuple[float, float, float]]] = []
    z_values: list[float] = []
    for iy in range(steps + 1):
        row: list[tuple[float, float, float]] = []
        y = ymin + (ymax - ymin) * iy / steps
        for ix in range(steps + 1):
            x = xmin + (xmax - xmin) * ix / steps
            try:
                z = _eval_surface_expr(expression, x, y)
                if not math.isfinite(z):
                    z = 0.0
            except Exception:
                z = 0.0
            z = max(min(z, 10.0), -10.0)
            z_values.append(z)
            row.append((x, y, z))
        raw.append(row)
    max_abs = max(abs(z) for z in z_values) or 1.0
    z_scale = 1.6 / max_abs
    vertices = [[(x, y, z * z_scale) for x, y, z in row] for row in raw]
    b = ObjBuilder(name)
    b.add_box(center=(0, 0, -0.06), size=(abs(xmax - xmin) + 0.4, abs(ymax - ymin) + 0.4, 0.04), material="base")
    b.add_surface(vertices=vertices, material="surface")
    path = workspace.assets_dir / f"{_safe_name(name)}.obj"
    path.write_text(b.text())
    return {
        "path": str(path),
        "name": _safe_name(name),
        "bounds": b.bounds(),
        "expression": expression,
        "x_range": [xmin, xmax],
        "y_range": [ymin, ymax],
        "steps": steps,
        "kind": "surface",
    }


def create_scatter_obj(
    points: Iterable[Iterable[float]],
    *,
    name: str = "visual_scatter_plot",
    point_size: float = 0.16,
    workspace: Workspace = Workspace(),
) -> dict[str, Any]:
    """Create a simple 3D scatter plot OBJ from xyz points."""
    workspace.ensure()
    parsed: list[tuple[float, float, float]] = []
    for point in points:
        values = [float(value) for value in point]
        if len(values) != 3:
            raise ValueError("scatter points must be [x, y, z] triples")
        parsed.append((values[0], values[1], values[2]))
    if not parsed:
        raise ValueError("scatter points must not be empty")
    if len(parsed) > 512:
        raise ValueError("scatter plot supports up to 512 points for now")

    safe = _safe_name(name)
    size = max(float(point_size), 0.01)
    b = ObjBuilder(safe)
    raw_bounds = bounds_from_points(parsed)
    center = tuple(float(value) for value in raw_bounds["center"])
    span_x = max(abs(raw_bounds["max"][0] - raw_bounds["min"][0]), size)
    span_y = max(abs(raw_bounds["max"][1] - raw_bounds["min"][1]), size)
    b.add_box(center=(center[0], center[1], float(raw_bounds["min"][2]) - size), size=(span_x + size * 2.0, span_y + size * 2.0, size * 0.2), material="base")
    for idx, point in enumerate(parsed):
        material = "point_highlight" if idx == 0 else "point"
        b.add_box(center=point, size=(size, size, size), material=material)
    path = workspace.assets_dir / f"{safe}.obj"
    path.write_text(b.text())
    return {"path": str(path), "name": safe, "kind": "scatter", "point_count": len(parsed), "bounds": b.bounds()}


def create_avatar_face_obj(
    *,
    name: str = "hermes_avatar_face",
    workspace: Workspace = Workspace(),
) -> dict[str, Any]:
    """Create a simple non-human Hermes avatar face for use as a scene guide."""
    workspace.ensure()
    safe = _safe_name(name)
    b = ObjBuilder(safe)
    b.add_ellipsoid(center=(0, 0, 1.25), radii=(0.95, 0.28, 1.18), material="face")
    b.add_box(center=(0, -0.28, 2.55), size=(0.22, 0.12, 0.25), material="crest")
    b.add_box(center=(0, -0.30, 0.05), size=(0.36, 0.12, 0.16), material="chin")
    for x in (-0.36, 0.36):
        b.add_box(center=(x, -0.42, 1.55), size=(0.25, 0.11, 0.12), material="eye")
        b.add_box(center=(x, -0.50, 1.55), size=(0.08, 0.08, 0.08), material="pupil")
    for i, x in enumerate([-0.32, -0.16, 0.0, 0.16, 0.32]):
        z = 0.84 - 0.10 * math.cos((i - 2) * math.pi / 4)
        b.add_box(center=(x, -0.43, z), size=(0.12, 0.10, 0.08), material="mouth")
    b.add_voxel_ring(center=(0, 0.08, 1.72), radius=1.35, voxel_size=0.08, count=56, material="halo")
    for i in range(4):
        b.add_box(center=(1.55 + 0.33 * i, -0.05, 1.1 + 0.18 * i), size=(0.22, 0.08, 0.16), material="thought")
    b.add_box(center=(0, 0, -0.08), size=(2.5, 1.05, 0.08), material="base")
    for x in (-0.78, 0.78):
        b.add_box(center=(x, -0.05, 2.15), size=(0.08, 0.08, 0.62), material="antenna")
        b.add_box(center=(x, -0.05, 2.52), size=(0.18, 0.18, 0.18), material="antenna")
    path = workspace.assets_dir / f"{safe}.obj"
    path.write_text(b.text())
    return {"path": str(path), "name": safe, "kind": "avatar_face", "bounds": b.bounds()}


def _vector3(value: Any, default: tuple[float, float, float]) -> tuple[float, float, float]:
    if not isinstance(value, (list, tuple)) or len(value) != 3:
        return default
    return (float(value[0]), float(value[1]), float(value[2]))


def create_primitive_obj(spec: dict[str, Any], *, scene_id: str = "scene", workspace: Workspace = Workspace()) -> dict[str, Any]:
    """Compile a scene manifest primitive object spec to an OBJ asset."""
    workspace.ensure()
    kind = str(spec.get("type") or "box")
    object_id = str(spec.get("id") or spec.get("name") or kind)
    safe = _safe_name(f"{scene_id}_{object_id}")
    transform = spec.get("transform") if isinstance(spec.get("transform"), dict) else {}
    translate = _vector3(transform.get("translate"), (0.0, 0.0, 0.0))
    scale = _vector3(transform.get("scale"), (1.0, 1.0, 1.0))
    material = str(spec.get("material") or "default")
    b = ObjBuilder(safe)

    if kind == "box":
        size = _vector3(spec.get("size"), (1.0, 1.0, 1.0))
        b.add_box(center=translate, size=(size[0] * scale[0], size[1] * scale[1], size[2] * scale[2]), material=material)
    elif kind == "sphere":
        radius = float(spec.get("radius", 1.0))
        b.add_ellipsoid(center=translate, radii=(radius * scale[0], radius * scale[1], radius * scale[2]), material=material)
    elif kind == "ellipsoid":
        radii = _vector3(spec.get("radii"), (1.0, 0.6, 0.4))
        b.add_ellipsoid(center=translate, radii=(radii[0] * scale[0], radii[1] * scale[1], radii[2] * scale[2]), material=material)
    elif kind == "cylinder":
        radius = float(spec.get("radius", 0.5)) * max(abs(scale[0]), abs(scale[1]))
        height = float(spec.get("height", 1.0)) * abs(scale[2])
        b.add_cylinder(center=translate, radius=radius, height=height, material=material)
    else:
        raise ValueError(f"unsupported primitive type {kind!r}")

    path = workspace.assets_dir / f"{safe}.obj"
    path.write_text(b.text(), encoding="utf-8")
    return {"path": str(path), "name": safe, "kind": kind, "format": "obj", "bounds": b.bounds()}


def scene_commands_for_asset(asset: dict[str, Any], *, material_name: str, color: list[float]) -> list[dict[str, Any]]:
    camera = camera_for_bounds(asset.get("bounds", {"center": [0.0, 0.0, 0.5], "radius": 3.0}))
    return [
        {"op": "import_geometry", "payload": {"path": asset["path"], "format": "obj", "name": asset["name"]}},
        {"op": "create_material", "payload": {"name": material_name, "kind": "glossy", "color": color, "roughness": 0.2}},
        {"op": "assign_material", "payload": {"object_name": asset["name"], "material_name": material_name}},
        {"op": "set_camera", "payload": camera},
        {"op": "set_lighting", "payload": {"preset": "soft_studio"}},
        {"op": "start_render", "payload": {"samples": 128, "width": 1280, "height": 1280}},
    ]
